name: Deploy to IIS (Self-hosted)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Publish Application
        run: dotnet publish --configuration Release --output C:\Temp\publish

      - name: Deploy to IIS
        shell: powershell
        run: |
          Import-Module WebAdministration

          # Stop Application Pool
          Stop-WebAppPool -Name "DefaultAppPool"
          Start-Sleep -Seconds 5

          # Backup current deployment (optional)
          $backupPath = "C:\Backups\mywebapp_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
          if (Test-Path "C:\inetpub\wwwroot\mywebapp") {
              Copy-Item -Path "C:\inetpub\wwwroot\mywebapp" -Destination $backupPath -Recurse
          }

          # Deploy new files
          Remove-Item -Path "C:\inetpub\wwwroot\mywebapp\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Path "C:\Temp\publish\*" -Destination "C:\inetpub\wwwroot\mywebapp" -Recurse -Force

          # Start Application Pool
          Start-WebAppPool -Name "DefaultAppPool"

          # Clean up
          Remove-Item -Path "C:\Temp\publish" -Recurse -Force
